In [ ]:
1:10
10:1
5:15
15:5
-1:-10
-10:-1

 [1]  1  2  3  4  5  6  7  8  9 10

 [1] 10  9  8  7  6  5  4  3  2  1

 [1]  5  6  7  8  9 10 11 12 13 14 15

 [1] 15 14 13 12 11 10  9  8  7  6  5

 [1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10

 [1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1

In [ ]:
seq(1,10,by=2)
seq(10, 1, by = -2)
seq(1.23, 10, by = 1)
seq(-5.23, 6, by = 1)

[1] 1 3 5 7 9

[1] 10  8  6  4  2

[1] 1.23 2.23 3.23 4.23 5.23 6.23 7.23 8.23 9.23

 [1] -5.23 -4.23 -3.23 -2.23 -1.23 -0.23  0.77  1.77  2.77  3.77  4.77  5.77

In [ ]:
seq(10)

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
x <- 50

seq(0, x, by = x/10)

 [1]  0  5 10 15 20 25 30 35 40 45 50

In [ ]:
x <- seq(1, 10, by = 0.5)

x

 [1]  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0
[16]  8.5  9.0  9.5 10.0

In [ ]:
y <- 2 * x

y

 [1]  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [ ]:
x <- c(9, 8, 7, 6)

In [ ]:
ind <- seq(along = x)

ind

[1] 1 2 3 4

In [ ]:
x[ind[2]]

[1] 8

In [ ]:
Sys.time()

[1] "2026-09-03 04:22:01 UTC"

In [ ]:
Sys.Date()

[1] "2026-09-03"

In [ ]:
seq(
  as.Date("2010-01-01"),
  as.Date("2017-01-01"),
  by = "years"
)

[1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
[6] "2015-01-01" "2016-01-01" "2017-01-01"

In [ ]:
seq(
  as.Date("2017-01-01"),
  by = "days",
  length = 6
)

[1] "2017-01-01" "2017-01-02" "2017-01-03" "2017-01-04" "2017-01-05"
[6] "2017-01-06"

In [ ]:
seq(
  as.Date("2017-01-01"),
  by = "months",
  length = 6
)

[1] "2017-01-01" "2017-02-01" "2017-03-01" "2017-04-01" "2017-05-01"
[6] "2017-06-01"

In [ ]:
seq(
  as.Date("2017-01-01"),
  by = "years",
  length = 6
)

[1] "2017-01-01" "2018-01-01" "2019-01-01" "2020-01-01" "2021-01-01"
[6] "2022-01-01"

In [ ]:
startdate <- as.Date("2016-01-01")
enddate <- as.Date("2017-01-01")

In [ ]:
out <- seq(
  enddate,
  startdate,
  by = "-1 month"
)

out

 [1] "2017-01-01" "2016-12-01" "2016-11-01" "2016-10-01" "2016-09-01"
 [6] "2016-08-01" "2016-07-01" "2016-06-01" "2016-05-01" "2016-04-01"
[11] "2016-03-01" "2016-02-01" "2016-01-01"

In [ ]:
seq(
  Sys.Date(),
  by = "days",
  length = 10
)

 [1] "2026-09-03" "2026-09-04" "2026-09-05" "2026-09-06" "2026-09-07"
 [6] "2026-09-08" "2026-09-09" "2026-09-10" "2026-09-11" "2026-09-12"

## **Sequence of alphhabets**

In [ ]:
letters

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [ ]:
letters[1:3]

[1] "a" "b" "c"

In [ ]:
letters[3:1]

[1] "c" "b" "a"

In [ ]:
letters[21:23]

[1] "u" "v" "w"

In [ ]:
letters[2]

[1] "b"

In [ ]:
LETTERS
LETTERS[1:3]
LETTERS[3:1]
LETTERS[21:23]
LETTERS[2]

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

[1] "A" "B" "C"

[1] "C" "B" "A"

[1] "U" "V" "W"

[1] "B"

## **Repeats**

In [ ]:
rep(3.5,times=10)
rep(1:4,2)

 [1] 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5

[1] 1 2 3 4 1 2 3 4

In [ ]:
x = 1:4
rep(x, each = 3)

 [1] 1 1 1 2 2 2 3 3 3 4 4 4

In [ ]:
rep(x, times = 3)

 [1] 1 2 3 4 1 2 3 4 1 2 3 4

In [ ]:
rep(x, each = 3)

 [1] 1 1 1 2 2 2 3 3 3 4 4 4

In [ ]:
rep(1:4, each = 2, times = 3)

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

In [ ]:
rep(1:4, 2:5)

 [1] 1 1 2 2 2 3 3 3 3 4 4 4 4 4

In [ ]:
x = matrix(
  nrow = 2,
  ncol = 2,
  data = 1:4,
  byrow = TRUE
)

x

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [ ]:
rep(c("a", "b", "c"), 2)
rep(c("apple", "banana", "cake"), 2)

[1] "a" "b" "c" "a" "b" "c"

[1] "apple"  "banana" "cake"   "apple"  "banana" "cake"

In [ ]:
rep(2, length.out = 5)
rep(c(2, 3), length.out = 5)

[1] 2 2 2 2 2

[1] 2 3 2 3 2

In [ ]:
rep_len(c(1, 2, 3), 8)

[1] 1 2 3 1 2 3 1 2

## **Sorting and Ordering**

In [ ]:
y = c(9, 8, 5, 7, 6)

sort(y)

[1] 5 6 7 8 9

In [ ]:
sort(y, decreasing = TRUE)

[1] 9 8 7 6 5

In [ ]:
order(y)

[1] 3 5 4 2 1

In [ ]:
order(y, decreasing = TRUE)

[1] 1 2 4 5 3

In [ ]:
y[order(y)]

[1] 5 6 7 8 9

In [ ]:
y[order(y, decreasing = TRUE)]

[1] 9 8 7 6 5

## **mode()**

In [ ]:
x = c(10, 20, 30, 40)
mode(x)

[1] "numeric"

In [ ]:
x = c("apple", "banana", "orange")
mode(x)

[1] "character"

In [ ]:
x = factor(c("Male", "Female", "Male"))
mode(x)

[1] "numeric"

In [ ]:
x = list(10, "hello", TRUE)
mode(x)

[1] "list"

In [ ]:
x = function(a) {
  a + 10
}

mode(x)

[1] "function"

## **Lists**

In [ ]:
x = list(10,"hello",TRUE)
x

[[1]]
[1] 10

[[2]]
[1] "hello"

[[3]]
[1] TRUE

In [ ]:
x1 = matrix(
  nrow = 2,
  ncol = 2,
  data = 1:4,
  byrow = TRUE
)

x1

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [ ]:
x2 = matrix(
  nrow = 2,
  ncol = 2,
  data = 5:8,
  byrow = TRUE
)

x2

     [,1] [,2]
[1,] 5    6
[2,] 7    8

In [ ]:
x1+x2

     [,1] [,2]
[1,]  6    8
[2,] 10   12

In [ ]:
x1[1,1] = "hello"
x1

     [,1]  [,2]
[1,] hello 2
[2,] 3     4

In [ ]:
x1+x2

ERROR: Error in x1 + x2: non-numeric argument to binary operator

In [ ]:
x1 = matrix(
  nrow = 2,
  ncol = 2,
  data = 1:4,
  byrow = TRUE
)

x2 = matrix(
  nrow = 2,
  ncol = 2,
  data = 5:8,
  byrow = TRUE
)

In [ ]:
matlist = list(x1, x2)

matlist

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [ ]:
matlist[1]

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

In [ ]:
matlist[2]

[[1]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [ ]:
matlist[[1]]
matlist[[2]]

     [,1] [,2]
[1,] 1    2
[2,] 3    4

     [,1] [,2]
[1,] 5    6
[2,] 7    8

In [ ]:
z1 = list(
  c("water", "juice", "lemonade"),
  rep(1:4, each = 2),
  matrix(
    data = 5:8,
    nrow = 2,
    ncol = 2,
    byrow = TRUE
  )
)

z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [ ]:
z1[[1]]

[1] "water"    "juice"    "lemonade"

In [ ]:
z1[[1]][2]

[1] "juice"

In [ ]:
students = list(
  Students = c("Rahul", "Amit", "Priya"),
  Marks = c(85, 90, 88)
)

students

$Students
[1] "Rahul" "Amit"  "Priya"

$Marks
[1] 85 90 88

In [ ]:
students[["Students"]]

[1] "Rahul" "Amit"  "Priya"

In [ ]:
z1 = list(
  c("water", "juice", "lemonade"),
  rep(1:4, each = 2),
  matrix(
    data = 5:8,
    nrow = 2,
    ncol = 2,
    byrow = TRUE
  )
)

z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [ ]:
z1[[2]]

[1] 1 1 2 2 3 3 4 4

In [ ]:
z1[[3]]

     [,1] [,2]
[1,] 5    6
[2,] 7    8

In [ ]:
z1[[3]][1,2]

[1] 6

In [ ]:
x = list(
  "Hello",
  list(10, 20, 30)
)

x

[[1]]
[1] "Hello"

[[2]]
[[2]][[1]]
[1] 10

[[2]][[2]]
[1] 20

[[2]][[3]]
[1] 30

In [ ]:
x[[2]][[2]]

[1] 20