## **Name: Chirag CHaudhari**
## **Roll no: 24102A2003**
## **Branch: CMPN - A**

## **Missing Data in R**

In [ ]:
x <- NA
x

[1] NA

In [ ]:
is.na(x)

[1] TRUE

In [ ]:
x <- c(11,NA,13,NA)
x

[1] 11 NA 13 NA

In [ ]:
is.na(x)

[1] FALSE  TRUE FALSE  TRUE

In [ ]:
mean(x)

[1] NA

In [ ]:
mean(x,na.rm = TRUE)

[1] 12

In [ ]:
x <- NA
y <- NULL

is.na(x)
is.null(x)

is.na(y)
is.null(y)

[1] TRUE

[1] FALSE

logical(0)

[1] TRUE

## **Find the positions of missing values**

In [ ]:
x <- c(11,NA,13,NA) #combine or concatenate

which(is.na(x))

[1] 2 4

In [ ]:
sum(is.na(x))

[1] 2

In [ ]:
complete.cases(x) # It checks each position to see if it contains valid, non-missing data.

[1]  TRUE FALSE  TRUE FALSE

In [ ]:
y <- na.omit(x) # remove missing values

y

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

In [ ]:
attr(y, "na.action")

[1] 2 4
attr(,"class")
[1] "omit"

In [ ]:
# Compare mean before and after
mean(x)
mean(y)

[1] NA

[1] 12

## **Conditional Execution**

In [ ]:
x <- 5

if(x>4){
  x*3
}

[1] 15

In [ ]:
x <- 3

if (x > 4) {
    x * 3
}

In [ ]:
x <- 6

if (x > 3) {
    print("The value is more than 3")
}

[1] "The value is more than 3"

In [ ]:
x <- 2

if (x > 3) {
    print("The value is more than 3")
}

In [ ]:
x <- 5

if (x == 3) {
    x <- x - 1
} else {
    x <- 2 * x
}

x

[1] 10

In [ ]:
x <- 3

if (x == 3) {
    x <- x - 1
} else {
    x <- 2 * x
}

x

[1] 2

In [ ]:
x <- 6

if (x > 3) {
    print("The value is more than 3")
} else {
    print("The value is less than 3")
}

[1] "The value is more than 3"

In [ ]:
x <- 2

if (x > 3) {
    print("The value is more than 3")
} else {
    print("The value is less than 3")
}

[1] "The value is less than 3"

## **Nested if...else if...else**

In [ ]:
x <- 5

if (x == 3) {
    x <- x - 1
} else if (x < 3) {
    x <- x + 5
} else {
    x <- 2 * x
}

x

[1] 10

In [ ]:
x <- 3

if (x == 3) {
    x <- x - 1
} else if (x < 3) {
    x <- x + 5
} else {
    x <- 2 * x
}

x

[1] 2

## **ifelse with vector**

In [ ]:
x <- 1:10

ifelse(x < 6, x^2, x + 1)

 [1]  1  4  9 16 25  7  8  9 10 11

In [ ]:
x <- c(7, 9, 8, 4)

ifelse(x %% 2 == 0, "even number", "odd number")

[1] "odd number"  "odd number"  "even number" "even number"

## **switch()**

In [ ]:
switch(2, "apple", "banana", "orange")

[1] "banana"

In [ ]:
switch(1, "apple", "banana", "orange")

[1] "apple"

In [ ]:
switch("colour",
       colour = "blue",
       gender = "male",
       volume = 50)

[1] "blue"

In [ ]:
switch("volume",
       colour = "blue",
       gender = "male",
       volume = 50)

[1] 50

In [ ]:
switch(4, "apple", "banana", "orange")

## **which()**

In [ ]:
x <- c(10, 15, 8, 14, 6, 12)

x

which(x == 14)

[1] 10 15  8 14  6 12

[1] 4

In [ ]:
which(x != 12)

[1] 1 2 3 4 5

In [ ]:
which(x > 10)

[1] 2 4 6

In [ ]:
x <- matrix(nrow = 3, ncol = 3, data = 1:9)

x

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

In [ ]:
which.min(x)

[1] 1

In [ ]:
which.max(x)

[1] 9

In [ ]:
which(x %% 2 == 1)

[1] 1 3 5 7 9

In [ ]:
which(x %% 2 == 1, arr.ind = TRUE)

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3

## **Conclusion**

The experiment provided a practical understanding of missing data handling and conditional execution in R. We learned to identify and handle missing values using is.na(), which(), sum(), complete.cases(), and na.omit(). We also implemented conditional statements using if, if...else, and else if, followed by vectorized conditional operations using ifelse(). Finally, we explored switch(), which.min(), which.max(), and which() with arr.ind = TRUE for locating values and their positions.